version: '3.9'

services:

  mongo:
    image: mongo
    container_name: rocketsoketbanco
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: andre
      MONGO_INITDB_ROOT_PASSWORD: rocketsoketdb
      MONGO_INITDB_DATABASE: rocketsoket
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  app:
    build: .
    container_name: rocketsoketapp
    restart: always
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    depends_on:
      - mongo


#https://stackoverflow.com/questions/42912755/how-to-create-a-db-for-mongodb-container-on-start-up